In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
# 모델
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression

In [2]:
real_dict = {"d25" : [0, 0, 0, 0, 0, 0,
                      0, 10, 31, 54, 70, 72, 78, 73, 63, 40, 20, 3, 0,
                      0, 0, 0, 0, 0],
             "d26" : [0, 0, 0, 0, 0, 0,
                      1, 3, 11, 40, 61, 52, 75, 61, 62, 40, 18, 2, 0,
                      0, 0, 0, 0, 0],
             "d27" : [0, 0, 0, 0, 0, 0,
                      1, 9, 36, 46, 53, 74, 89, 81, 64, 54, 23, 4, 0,
                      0, 0, 0, 0, 0],
             "d28" : [0, 0, 0, 0, 0, 0,
                      0, 5, 29, 56, 67, 82, 78, 72, 63, 46, 17, 3, 0,
                      0, 0, 0, 0, 0],
             "d29" : [0, 0, 0, 0, 0, 0,
                      0, 4, 20, 56, 66, 76, 53, 57, 66, 42, 20, 2, 0,
                      0, 0, 0, 0, 0],
             "d30" : [0, 0, 0, 0, 0, 0,
                      0, 4, 20, 56, 65, 79, 81, 75, 62, 45, 22, 3, 0,
                      0, 0, 0, 0, 0],
             "d31" : [0, 0, 0, 0, 0, 0,
                      0, 4, 8, 22, 37, 76, 73, 75, 58, 44, 22, 4, 0,
                      0, 0, 0, 0, 0]}

In [3]:
## test data set 만드는 함수
def make_test_xy(wf,gf):
    gf.columns = ["time","m0","m1","m2","m3","m4"]
    train = pd.merge(gf,wf,on="time")
    train["time"] = pd.to_datetime(train["time"])
    train["month"]=train["time"].dt.month
    train["day"]=train["time"].dt.day
    train["hour"]=train["time"].dt.hour
    
    train_1 = train[(train["hour"]<=10) & (train["hour"]>=7)]
    train_2 = train[(train["hour"]<=14) & (train["hour"]>=11)]
    train_3 = train[(train["hour"]<=19) & (train["hour"]>=15)]
    
    train11 = train_1[["m0","m1","m2","m3","uv_idx","elevation"]]
    train12 = train_2[["m0","m1","m2","m3","uv_idx","elevation"]]
    train13 = train_3[["m0","m1","m2","m3","uv_idx","elevation"]]
    train21 = train_1.drop(["m0","m1","m2","m3","m4","uv_idx","elevation","time","hour"],axis=1)
    train22 = train_2.drop(["m0","m1","m2","m3","m4","uv_idx","elevation","time","hour"],axis=1)
    train23 = train_3.drop(["m0","m1","m2","m3","m4","uv_idx","elevation","time","hour"],axis=1)
    
    return train11,train12,train13,train21,train22,train23

#  예측 진행

In [69]:
# 예측에 사용할 데이터 셋 불러오기 
x_pred_ori = pd.read_csv("../data/gen_fcst_10_2023-10-31.csv")
x_pred_wf = pd.read_csv("../data/weather_forecasts/wf10_2023-10-31.csv")

In [81]:
day = real_dict["d31"]

In [82]:
# 함수에 넣어서 데이터셋 분리
test11,test12,test13,test21,test22,test23 = make_test_xy(x_pred_wf,x_pred_ori)

In [33]:
import joblib

In [84]:
model11=joblib.load("../model/시간1회귀fitting_season10-11_r1.pkl")
model12=joblib.load("../model/시간2회귀fitting_season10-11_r1.pkl")
model13=joblib.load("../model/시간3회귀fitting_season10-11_r1.pkl")
# 예측 진행 (1차 모델링 y_hat)
y_pred11=model11.predict(test11)
y_pred12=model12.predict(test12)
y_pred13=model13.predict(test13)
model21=joblib.load("../model/시간1잔차fitting_season10-11_r1.pkl")
model22=joblib.load("../model/시간2잔차fitting_season10-11_r1.pkl")
model23=joblib.load("../model/시간3잔차fitting_season10-11_r1.pkl")
y_pred21 = model21.predict(test21)
y_pred22 = model22.predict(test22)
y_pred23 = model23.predict(test23)
result1 = y_pred11+y_pred21
result2 = y_pred12+y_pred22
result3 = y_pred13+y_pred23
result = np.concatenate((result1,result2,result3))
res1 = result

In [85]:
res1

array([ 1.84859966e+00,  4.90431195e+00,  2.33039269e+01,  4.29479318e+01,
        5.83683362e+01,  7.07005880e+01,  7.43051735e+01,  6.66335775e+01,
        5.01526925e+01,  3.81825024e+01,  9.87912963e+00,  7.09053865e-02,
       -3.93687518e-01])

In [86]:
# 예측에 사용할 데이터 셋 불러오기 
x_pred_ori = pd.read_csv("../data/gen_fcst_17_2023-10-31.csv")
x_pred_wf = pd.read_csv("../data/weather_forecasts/wf17_2023-10-31.csv")
# 함수에 넣어서 데이터셋 분리
test11,test12,test13,test21,test22,test23 = make_test_xy(x_pred_wf,x_pred_ori)

In [87]:
model11=joblib.load("../model/시간1회귀fitting_season10-11_r2.pkl")
model12=joblib.load("../model/시간2회귀fitting_season10-11_r2.pkl")
model13=joblib.load("../model/시간3회귀fitting_season10-11_r2.pkl")
# 예측 진행 (1차 모델링 y_hat)
y_pred11=model11.predict(test11)
y_pred12=model12.predict(test12)
y_pred13=model13.predict(test13)
model21=joblib.load("../model/시간1잔차fitting_season10-11_r2.pkl")
model22=joblib.load("../model/시간2잔차fitting_season10-11_r2.pkl")
model23=joblib.load("../model/시간3잔차fitting_season10-11_r2.pkl")
y_pred21 = model21.predict(test21)
y_pred22 = model22.predict(test22)
y_pred23 = model23.predict(test23)
result1 = y_pred11+y_pred21
result2 = y_pred12+y_pred22
result3 = y_pred13+y_pred23
result = np.concatenate((result1,result2,result3))
res2 = result

In [88]:
res2

array([ 0.18596756,  6.01518928, 26.87180759, 50.19747106, 70.2499242 ,
       76.6229421 , 72.96244177, 73.3144415 , 62.37336357, 40.73082001,
       16.97671082,  3.58966611, -0.6802562 ])

In [89]:
pred = (res1+res2)/2

In [90]:
pred

array([ 1.01728361,  5.45975062, 25.08786724, 46.57270141, 64.30913021,
       73.66176503, 73.63380766, 69.9740095 , 56.26302805, 39.45666122,
       13.42792022,  1.83028575, -0.53697186])

In [91]:
pred = [0,0,0,0,0,0, 
        1.01728361,  5.45975062, 25.08786724, 46.57270141, 64.30913021,
       73.66176503, 73.63380766, 69.9740095 , 56.26302805, 39.45666122,
       13.42792022,  1.83028575, -0.53697186,
       0,0,0,0,0]

In [16]:
import numpy as np

def testMSEnIncentive(pred,day):
    realGens1030 = np.array(day)    
    
    rss = np.power(pred - realGens1030, 2)
    rss1 = rss[6:10]
    rss2 = rss[10:14]
    rss3 = rss[14:19]
    mse1 = sum(rss1/len(rss1))
    mse2 = sum(rss2/len(rss2))
    mse3 = sum(rss3/len(rss3))
    mse = [mse1,mse2,mse3]

    score_df = abs(pred - realGens1030)*100/99
    score = []
    for idx, i in enumerate(score_df):
        if i <=6:
            score.append(realGens1030[idx] * 4)
        elif (i <=8) & (i > 6):
            score.append(realGens1030[idx] * 3)
        else:
            score.append(0)
    score1 = score[6:10]
    score2 = score[10:14]
    score3 = score[14:19]
    final_score = [score1,score2,score3]
    
    sum_score = sum(score)

    return mse, final_score , score, sum_score

In [92]:
testMSEnIncentive(pred,day)

([224.74464980316156, 194.22955706440771, 20.427109856941687],
 [[0, 16, 0, 0], [0, 304, 292, 300], [232, 176, 0, 16, 0]],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  16,
  0,
  0,
  0,
  304,
  292,
  300,
  232,
  176,
  0,
  16,
  0,
  0,
  0,
  0,
  0,
  0],
 1336)